application: gcpugjp-dev
module: default
version: 1
runtime: go
api_version: go1.9
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.75
  target_throughput_utilization: 0.75
  max_instances: 10
  min_instances: 5
  max_idle_instances: automatic  # default value
  min_idle_instances: 3
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 80

handlers:
- url: /api/cron/.*
  login: admin
  script: _go_app
- url: /api/admin/.*
  login: admin
  script: _go_app
- url: /swagger-ui
  static_dir: swagger-ui
  login: admin
- url: /_ah/warmup
  script: _go_app
  login: admin
- url: /.*
  script: _go_app

inbound_services:
- warmup